data:
  start_date: '2019-01-01'
  end_date: '2023-08-09'
  wrf_folder: '/home/wrf_data/'
  era_folder: '/home/era_data/'
  scatter_folder: '/home/scatter/'
  stations_folder: '/home/stations/interp/'
  wrf_mean_path: "/home/metadata/means_dict"
  wrf_std_path: "/home/metadata/stds_dict"
  base_folder: '/home'
  logs_folder: "/home/logs/"
  wrf_variables: ['uvmet10', 'T2', 'SEAICE', 'HGT']
  era_variables: ['u10', 'v10', 't2m']
  
model:
  name: MaskFeat
  group_size: 32
  num_group: 128
  svm_pool: max
  loss: cd1
  normal_loss: cos

  transformer_config:
    mask_ratio: 0.6
    mask_type: 'rand'
    trans_dim: 384
    encoder_dims: 384
    depth: 12
    drop_path_rate: 0
    num_heads: 6
    decoder_depth: 4
    decoder_num_heads: 6
